### ISSUE TITLE
Questions from a new user (Verbosity, caching, etc.)

### ISSUE THREAD

**Issue by forthrin** [HoneyryderChuck/httpx#12]
I'm switching from net/http because it doesn't support HTTP/2, and has a clunky way of setting up POST requests, etc.

Let me know is the gem supports (or could support) any of the below:

1. Fine-tuning of verbosity, ie. print a selection of some of the below (with helpful ANSI colors)
- a pretty-print of the request about to be sent
- redirect notices
- the full response header (and raise an exception) if an error occured (ie. not 200 or 3xx)?
- ETA
- a selection of nice progress bars (with an optional callback for the user to render his own)
- milliseconds the request actually took
2. Local cache stored as a mirror tree where the *user* controls expiration. (I wrote one myself in lack of finding one.)
3. Automatic `JSON.parse` for a JSON response body
4. Convert cURL requests from CLI or Ruby (very useful when getting these from a browser console!)

Also, is verbosity covered anywhere in the Wiki? (I found this the best place to learn, as the rdoc was rather cryptic.)

**Comment by HoneyryderChuck** [comment]
👋 

1. Make sure to read [the debugging section of the wiki](https://honeyryderchuck.gitlab.io/httpx/wiki/Debugging), which contains tips about logging and verbosity levels.
2. Do you mean [something like this](https://honeyryderchuck.gitlab.io/httpx/wiki/Response-Cache) ?
3. Do you mean [.json](https://honeyryderchuck.gitlab.io/httpx/wiki/Response-Handling#response-decoding)?
4. Currently only possible [from the main website](https://honeyryderchuck.gitlab.io/httpx/). The script generating javascript [is mostly ruby though](https://gitlab.com/honeyryderchuck/honeyryderchuck.gitlab.io/-/blob/master/scripts/curl_to_ruby.js.rb), so feel free to adapt and extend.

Overall, the wiki is the best place to check documentation about how to use httpx, definitely. There you'll find answers to some of the other questions you asked, such as "how to raise an exception for not 200 or 3xx", "how to follow redirects", and more.

**Comment by forthrin** [comment]
1. The link is scarce (does not list debug levels, or what they pertain). Even debug level 0 is way too verbose. Go over my enclosed list again, point by point. I'm looking for very terse and specific output. Maybe this is best done as a wrapper, since most of it happens before or after the request. However the progress bar (and redirect) would need an internal implemention (and potential user callbacks). Does this exist (or could be implemented)? 
2. Scarce information about how this works and how files are stored on the local hard drive. I mean something like `cache("http://example.com/folder/file.html", expire: 86_400)` which would store a local copy in `~/Downloads/Cache/example.com/folder/file.html` and not contact the server again until the local file was 24 hours old.
3. Nice! However I would almost expect this to be a default. I mean, when do you not want to decode it?
4. I'll have a look.

Yep, those common topics will no doubt have an elegant solution.

**Comment by HoneyryderChuck** [comment]
1. Anything very specific will not be solved by httpx's default logging capabilities, which are designed to help me with debugging reported issues. You're best served with [building your own plugin](https://honeyryderchuck.gitlab.io/httpx/wiki/Custom-Plugins) and interfacing specific points (or alternatively, you can [pick up or finish this MR which didn't get enough traction, or adapt it to your needs](https://gitlab.com/os85/httpx/-/merge_requests/201)).
2. About docs, fair enough. The default (currently only) store keeps them in memory. However, not sure again if it fits your needs. If you want to control cache busting, perhaps a custom plugin serves you best.
3. httpx is a generic http client. The internet is more than JSON ;) I think that `response.json` is terse enough.

**Comment by forthrin** [comment]
1. I'll make my own wrapper for the before/after things. I'll check the code for somewhere to add a callback to a progress/ETA meter, eg. whenever a new chunk of data is received. Pointers appreciated.
2. Nope, this is persistent disk storage of "never" or "seldom" changing remote data. Again, easy to do as a wrapper, which I've done. Just thought that other people could benefit from this, or maybe had written something already.
3. Absolutely :)

Very nice and friendly talk.

**Comment by forthrin** [comment]
How does one subclass HTTPX?

```
module HTTPY
  include HTTPX
  module Chainable
    def get(*uri, **options)
      puts 'HTTPY'
      super
    end
  end
end

class HTTPZ
  include HTTPX
  def self.get(*uri, **options)
    puts 'HTTPZ'
    HTTPX.get(uri, options)
  end
end

puts HTTPY.get('http://localhost:8080/?y') # undefined method (get)
puts HTTPZ.get('http://localhost:8080/?z') # bad argument (URI)
```

**Comment by HoneyryderChuck** [comment]
```
class HTTPZ < HTTPX::Session
```

Though I don't recommend inheritance. 

For future usability questions, please use the discussions section, and open a different discussion for each question you may have.
