### ISSUE TITLE
httpx fails on Windows out of the box (Ruby 3.2.1 and 2.7.3)

### ISSUE THREAD

**Issue by pcopissa** [HoneyryderChuck/httpx#19]
0) installed Ruby 3.2.1 + MSYS2 from rubyInstaller.org
1) find in start menu _Start Command Prompt with Ruby_ and execute it (starts ```cmd``` with appropriate path)
2) in cmd window:
```
>gem install httpx
...
2 gems installed
>ruby -v
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x64-mingw-ucrt]
>ruby -r httpx -e 'HTTPX.get("https://honeyryderchuck.gitlab.io")'
C:/Users/pcopissa/.gem/ruby/3.2.0/gems/httpx-1.0.2/lib/httpx/resolver/native.rb:365:in `generate_candidates': undefined method `<=' for nil:NilClass (NoMethodError)

      candidates = [name] if @ndots <= name_parts.size - 1
                                    ^^
...
```

Thanks nonetheless for your work on that promising gem.

BTW is GitHub ok for submitting issues ? Or do you prefer GitLab ?

Regards

**Comment by HoneyryderChuck** [comment]
Hi @pcopissa  thx for the report.

While I prefer gitlab, I understand not everyone will have or want to have an account there, hence why allow issues in this repo to be created. no worries there.

In order to narrow this down, can you open an irb console an run this code?:

```ruby
require "resolv"
Resolv::DNS::Config.default_config_hash
```

(do redact information that I may not need to know, like IPs or any confidential info).

**Comment by pcopissa** [comment]
Well I ended up creating an account on GitLab anyway...

Here you go:
```
irb(main):001:0> require "resolv"
=> true
irb(main):002:0> Resolv::DNS::Config.default_config_hash
=> {:nameserver=>["192.168.159.7"]}
irb(main):003:0>
```
I am using a cellphone hotspot to connect and that IP appears to be the phone:
```
>ipconfig
...
Scheda LAN wireless Wi-Fi:

   Suffisso DNS specifico per connessione:
   Indirizzo IPv6 locale rispetto al collegamento . : fe80::da3d:a790:fd13:ef8d%4
   Indirizzo IPv4. . . . . . . . . . . . : 192.168.159.71
   Subnet mask . . . . . . . . . . . . . : 255.255.255.0
   Gateway predefinito . . . . . . . . . : 192.168.159.7
```

**Comment by HoneyryderChuck** [comment]
Can you confirm whether https://gitlab.com/os85/httpx/-/merge_requests/283 fixes your issue?

**Comment by pcopissa** [comment]
I applied your patch on both copies of the gem (Ruby 2.7.3 and 3.2.1) and the issue is fixed in both. The error no longer appears and I do get back a response object from which I can get a body (for instance).

Than you very much and I think i will now be able to move from ```rest-client``` to ```httpx``` :-)

**Comment by HoneyryderChuck** [comment]
Thx for the feedback, I'll close this once I merge.

**Comment by HoneyryderChuck** [comment]
merged to master.
