### ISSUE TITLE
Deflate algorithm on request is incorrect

### ISSUE THREAD

**Issue by derigible** [HoneyryderChuck/httpx#20]
First off, love the gem! I learned about it in ruby weekly and decided to give it a go and definitely am a fan of the api.

One issue I am having however is that the deflate algorithm for compression doesn't seem to be working correctly. Below is a script that you can run to verify the bad behavior and the monkey patched fix:

```
basic_auth_header = { 'Authorization' => "Basic a" }

# uncomment to see the monkey patch fixing the issue
# module HTTPX
#   module Transcoder
#     module Deflate
#       class Inflater
#         def initialize(bytesize)
#           @inflater = Zlib::Inflate.new(Zlib::MAX_WBITS * -1)
#           @bytesize = bytesize
#         end

#         def call(chunk)
#           buffer = @inflater.inflate(chunk)
#           @bytesize -= chunk.bytesize
#           if @bytesize <= 0
#             buffer << @inflater.finish
#             @inflater.close
#           end
#           buffer
#         end
#       end

#       module_function

#       def decode(response, bytesize: nil)
#         bytesize ||= response.headers.key?('content-length') ? response.headers['content-length'].to_i : Float::INFINITY
#         Inflater.new(bytesize)
#       end
#     end
#   end
# end

# errors out below with `incorrect header check (HTTP2Next::Error::ProtocolError)`
users_resp = HTTPX.get(
  'https://profiles.segment.com/v1/spaces/a/collections/users/profiles'
)
```

It would also be a nice addition to the api to enable no compression/decompression (ie don't just remove the `accepts-encoding` header on range, but also allow for an option to remove it just cuz).

The monkeypatch is working well for me now, but I would be interested in know if this is something that is a problem with HTTPX, or if there are other instances of this failing.

**Comment by HoneyryderChuck** [comment]
Hey @derigible , thx for giving it a try, and for the issue reproduction.  I'll give it a go tomorrow.

**Comment by HoneyryderChuck** [comment]
added https://gitlab.com/os85/httpx/-/merge_requests/285 .

FYI I believe the majority of clients has the same configuration for "deflate", and would therefore break. They don't due to "accept-encoding" configurations.

For example, `httpx` sets `accept-encoding: gzip, deflate`. The server from the request you shared does not seem to honor the order, as it serves a deflated response.

´net-http` sets `accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3`. In this case, the server willl prefer gzip, which net-http decodes well. However, if you manually set the same value as `httpx`, it'll also fail to decode:

```ruby
require "uri"
require "net/http"

uri = URI('https://profiles.segment.com/v1/spaces/a/collections/users/profiles')
http = Net::HTTP.new(uri.host, uri.port)
http.set_debug_output($stdout)
req = Net::HTTP::Get.new(uri.request_uri)
# fails with below setting
# req["accept-encoding"] = "deflate,identity"
response = http.request(req)
puts response.body

```

perhaps smth you'd like to share with them.

**Comment by derigible** [comment]
Yeah, i thought that might be the case as well and plan to share this with them today. Thanks for looking into it! Appreciate the quick response. 

Should I close this now that the PR is up?

**Comment by HoneyryderChuck** [comment]
seems that this change [broke the tests](https://gitlab.com/os85/httpx/-/jobs/5364607500). Do you know of a reason why this configuration would not work for [httpbin deflate endpoint](https://httpbin.org/#/Response_formats/get_deflate)?

**Comment by derigible** [comment]
hmmm... i am not really familiar with the internals of http clients, but I can dig into this and see what I find.

**Comment by derigible** [comment]
The more I play around with this the more I think that the servers are delivering a compression that is possibly not deflate. The only way I can get the servers to work is by turning off the compression checks (https://ruby-doc.org/stdlib-2.7.0/libdoc/zlib/rdoc/Zlib/Inflate.html - turning it to -15 as the value). Even using 0 as the value returns an error, so I am not sure what algorithm they are using, but it isn't standard.

Of note is, when I hit this endpoint with curl and compression, it seems to work fine.

```
curl https://profiles.segment.com/v1/spaces/a/collections/users/profiles -v --compressed
*   Trying 44.239.154.195:443...
* Connected to profiles.segment.com (44.239.154.195) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.segment.com
*  start date: Feb 10 00:00:00 2023 GMT
*  expire date: Jan 12 23:59:59 2024 GMT
*  subjectAltName: host "profiles.segment.com" matched cert's "*.segment.com"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
*  SSL certificate verify ok.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: profiles.segment.com]
* h2 [:path: /v1/spaces/a/collections/users/profiles]
* h2 [user-agent: curl/8.1.2]
* h2 [accept: */*]
* h2 [accept-encoding: deflate, gzip]
* Using Stream ID: 1 (easy handle 0x129810e00)
> GET /v1/spaces/a/collections/users/profiles HTTP/2
> Host: profiles.segment.com
> User-Agent: curl/8.1.2
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
< HTTP/2 401 
< date: Tue, 24 Oct 2023 22:02:53 GMT
< content-type: application/json
< content-length: 82
< content-encoding: deflate
< www-authenticate: Basic realm="Token required"
< x-api-version: 2018-01-18
< x-request-id: ff809394-52c2-4849-831e-f429633f0943
< 
{
  "error": {
    "code": "unauthorized",
    "message": "missing authorization header"
  }
* Connection #0 to host profiles.segment.com left intact
}%    
```

But it doesn't work in curl when implementing a custom header -

```
curl https://profiles.segment.com/v1/spaces/a/collections/users/profiles -v -sH 'Accept-Encoding: gzip,deflate' | gunzip -
```

This returns the error being seen in ruby.

Perhaps curl is doing a fall back to not checking the compression header in the service of getting the data? 

I did realize i was spelling my `accept-encoding` header incorrectly, which is why it wasn't overriding the default compression being added in the first place. As a suggestion it might be nice to add a simple flag like `response_compression: false` or something along those lines to make it easier to opt out of compression.

At any rate, I don't think this is a problem specifically with HTTPX and my monkeypatch doesn't seem to be of much value. Thanks for taking the time to work with me on it though.
