### ISSUE TITLE
Unexpectedly returns gzip-ed body (didn't happen yesterday)

### ISSUE THREAD

**Issue by forthrin** [HoneyryderChuck/httpx#23]
```ruby
puts HTTPX.get('https://www.lanullva.no/', headers: { 'User-Agent' => 'Mozilla/5.0 (X11; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0' }).body
```

**Comment by HoneyryderChuck** [comment]
Hi @forthrin , thx for the report. Which version of HTTPX is this about?

**Comment by forthrin** [comment]
```
$ gem info httpx              
httpx (1.1.4)
```

I update gems every morning, so it must have updated from whichever version came before. This could be caused by a change on the website, but whatever the reason, no-one expects a compressed body (or the Spanish Inquisition).

**Comment by Earlopain** [comment]
I can reproduce on latest master.

In addition to this, the response claims a status code of `103 Early Hints`. The headers contain `:status => "200"`, is that expected? It feels like that should have been processed before somehow.

**Comment by forthrin** [comment]
I have also gotten `103` before, elsewhere. Yes, `1xx` are temporary, so returning as final is contradictory. The library should do eg. `raise unless response.status.between?(200, 599)` before returning, so errors can be caught and fixed.

**Comment by HoneyryderChuck** [comment]
Have a branch with a fix [here](https://gitlab.com/os85/httpx/-/merge_requests/308).

**Comment by HoneyryderChuck** [comment]
merged. feel free to try the master branch.

**Comment by forthrin** [comment]
WFM! Well `PUT` :)
