### ISSUE TITLE
VCR gem

### ISSUE THREAD

**Issue by pioz** [HoneyryderChuck/httpx#30]
Hi, I'm porting my project from Faraday to HTTPX.

All works great but in my test suite the gem [VCR](https://github.com/vcr/vcr) seems dont work anymore with httpx. VCR do not records the cassette .yml files. My setup in `test_helper.rb` is:

```
# Setup VCR
VCR.configure do |config|
  config.cassette_library_dir = 'test/vcr_cassettes'
  config.hook_into :webmock
  # config.allow_http_connections_when_no_cassette = true
end
```

If I switch back to Faraday, the gem record cassettes again. Any advice? I miss some extra conf that is needed to work with httpx?

**Comment by HoneyryderChuck** [comment]
Hi @pioz ,

VCR does not support httpx AFAIK. There seems to be a webmock-vcr integration which has been working for some though, and there are some commits related with webmock-vcr support in the master branch. Can you perhaps try your tests using the master branch and lmk whether that fixes your issue?

**Comment by pioz** [comment]
> Hi @pioz ,
> 
> VCR does not support httpx AFAIK. There seems to be a webmock-vcr integration which has been working for some though, and there are some commits related with webmock-vcr support in the master branch. Can you perhaps try your tests using the master branch and lmk whether that fixes your issue?

Just tried with `gem 'vcr', github: 'vcr/vcr', branch: :master` but it does not work. :(

**Comment by HoneyryderChuck** [comment]
I meant httpx master branch, not vcr. But since you closed it, we're you able to verify?
