### ISSUE TITLE
Callbacks, Retries, Circuit Breaker

### ISSUE THREAD

**Issue by Aubermean** [HoneyryderChuck/httpx#33]
I have noticed that the order of the plugins retries and the circuit breaker must come before any callbacks, for the callbacks not to be overriden. I wanted to make sure though, that its OK to use custom callbacks and retries/circuit breaker all together? Maybe a tip in the docs/wiki will help others if they have the same strange issues happening and get stuck all afternoon like I did!

**Comment by HoneyryderChuck** [comment]
Hi @Aubermean ,

Which callbacks are you talking about? Can you post a reproduction? 

Plugins should be order-independent, although they may accidentally not be (which can be fixed), except in the very few exceptions that are.
