### ISSUE TITLE
`ResponseCache` looking for the wrong last modified header

### ISSUE THREAD

**Issue by nvladimiroff** [HoneyryderChuck/httpx#49]
It looks like the ResponseCache plugin might be looking for the wrong last modified header when deciding whether to cache a response.

In https://github.com/HoneyryderChuck/httpx/blob/master/lib/httpx/plugins/response_cache.rb#L43, it's looking for `response.headers.key?("last-modified-at")`, however it looks like the correct header is just `Last-Modified` (with no `-at`): https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified

**Comment by HoneyryderChuck** [comment]
@nvladimiroff thx for the report. Indeed, you are correct, that seems to be the wrong header. Do you want to open a PR?
