### ISSUE TITLE
Unable to successfully complete concurrent requests when using the Faraday adaptor

### ISSUE THREAD

**Issue by scottroth** [HoneyryderChuck/httpx#61]
Hi - I'm having nothing but problems with typhoeus recently, so am looking for a replacement that supports Faraday's in_parallel functionality and that led me to you. This is a large existing project, so a drop-in Faraday adaptor would be wonderful. Unfortunately, I'm not able to get a "hello world" example running in irb:

```
require 'faraday'
require 'httpx/adapters/faraday'

connection = Faraday.new(url: 'https://news.ycombinator.com') do |faraday|
  faraday.adapter :httpx
end

connection.in_parallel do
  response1 = connection.get('/news')
  response2 = connection.get('/news?page=2')
end
```

It is reproducibly failing in adaptor code:
```
httpx-1.3.0/lib/httpx/adapters/faraday.rb:215:in `block (2 levels) in run': undefined method `call' for nil:NilClass (NoMethodError)
```

This is with Faraday 2.5.2 and ruby 2.7.6.  Any ideas are appreciated!

**Comment by HoneyryderChuck** [comment]
hey @scottroth thx for the report.

Indeed, this "on_complete" calllback isn't defined anywhere by default, and I'm not sure why it's there in the first place. I'm going to remove it, unless I find evidence of prior use.
