### ISSUE TITLE
Cannot generate RBI file for httpx gem

### ISSUE THREAD

**Issue by Aubermean** [HoneyryderChuck/httpx#62]
I've got an issue where Tapioca (a tool for type checking with Sorbet) is unable to generate an RBI file for this gem. I get an empty RBI file, which prevents type checking and IDE support for those using httpx... is there a quick and easy fix? Is [this](https://github.com/Shopify/tapioca?tab=readme-ov-file#manually-requiring-parts-of-a-gem) the issue? I have about 600 gems installed and no problems with the others. Thanks!

**Comment by HoneyryderChuck** [comment]
Hi @Aubermean ,

I'm not familiar with tapioca. httpx ships with RBS definitions, and I've heard of tools (don't know which) which translate RBS to something sorbet can parse. Is that an alternative? Otherwise, how can one reproduce this?

**Comment by HoneyryderChuck** [comment]
Feel free to reopen once you find a way to reproduce it.
