### ISSUE TITLE
error with vcr in version 1.3.2

### ISSUE THREAD

**Issue by jnvillar** [HoneyryderChuck/httpx#65]
With httpx version 1.3.1 my vcr tests where working just fine. Now I updated to version 1.3.2 and I am getting this error 

```
Failure/Error: res = ht_conn.post("/api/clients/carts", { client_id: params.client_id }.compact)
     
     ArgumentError:
       VCR::Request initialized with an invalid (non-String) body of class #<Class:0x000000011caddfc8>: #<HTTPX::Request::Body:49160 @bytesize=22>.`

```

this is how I am using httpx in the code

```
require "httpx/adapters/faraday"
...
...

def conn
 Faraday.new(url: BASE_URL) do |conn|
        conn.request :json
        conn.response :json
        conn.adapter :httpx, persistence: false
        conn.headers["Api-Key"] = API_KEY
        conn.headers["Content-Type"] = "application/json"
      end
end
```

then, in my tests, in my rails_helper.rb file I have at the top

```
require 'spec_helper'
require 'webmock/rspec'
require 'httpx'
require 'httpx/adapters/webmock'
require 'support/simplecov_helper'
```

and VCR is configured like this

```
VCR.configure do |config|
  config.ignore_localhost = true
  config.ignore_hosts 'localhost', '127.0.0.1', 'sqs.us-east-1.localhost.localstack.cloud'
  config.default_cassette_options[:allow_unused_http_interactions] = false
  config.cassette_library_dir = 'spec/vcr_cassettes'
  config.hook_into(:webmock)
  config.configure_rspec_metadata!
  config.default_cassette_options = { decode_compressed_response: true }
  config.before_record do |i|
    i.response.body.force_encoding('UTF-8')
  end

  {
    "SERVICE_API_KEY" => SomeService.api_key,
  }.each do |key, value|
    config.filter_sensitive_data("<#{key}>") { value }
  end
end
```

**Comment by HoneyryderChuck** [comment]
Hi @jnvillar , thx for the report.

I suspect that 4a966d4cb8396ca6337843abe15ab8292e341632 may have caused that regression. can you confirm by reverting the commit and trying out locally?

The full backtrace would also help, specifically on which line of vcr's webmock integration a string body is expected.I feel that's a bug in vcr, but I'd like to confirm it first.

**Comment by jnvillar** [comment]
I added this to my gemfile

```
gem 'httpx', git: 'https://github.com/HoneyryderChuck/httpx.git', ref: '4a966d4cb8396ca6337843abe15ab8292e341632'
```

and then run `bundle install`

then I run my tests and I got the same error

This is an example of the error trace I am seeing in the terminal (only lines that belong to my app)

```
  0) HelloTech::Client.get_cart when the cart exists gets the cart
     Failure/Error: res = ht_conn.post("/api/clients/carts", { client_id: params.client_id }.compact)

     ArgumentError:
       VCR::Request initialized with an invalid (non-String) body of class #<Class:0x00000001294c4300>: #<HTTPX::Request::Body:11360 @bytesize=22>.
     # ./app/infrastructure/hello_tech/client.rb:155:in 'HelloTech::Client#create_cart'
     # ...
     # ...
     # ...
     # ...
```

ht_conn is 

```
def conn
 Faraday.new(url: BASE_URL) do |conn|
        conn.request :json
        conn.response :json
        conn.adapter :httpx, persistence: false
        conn.headers["Api-Key"] = API_KEY
        conn.headers["Content-Type"] = "application/json"
      end
end
```

**Comment by HoneyryderChuck** [comment]
You have to run against the previous commit. It's easier if you clone the repo locally, point to the path in the gemfipe, and revert the commit.

Are you sure there aren't backtrack entries related to the vcr? Other than that, I'll need a repro script. I'm sure this is reproducible with any url which accepts a post request.

**Comment by jnvillar** [comment]
I found it simpler to just add the commit in the gemfile

If I point httpx gem to `70f1ffc65dd853e565670a5022f2e1ee8c345000` the tests run just fine

**Comment by jnvillar** [comment]
btw, I cloned the repo and reverted only that commit as you said and the tests are running fine also

**Comment by jnvillar** [comment]
another find

If I undo this change

[](https://github.com/HoneyryderChuck/httpx/commit/4a966d4cb8396ca6337843abe15ab8292e341632#diff-31072fd1b7d98f91ab466eef74d5b516c1831d45f798d66953a6cab1b1a68631L23)

then the error is gone
