### ISSUE TITLE
No way to handle invalid encodings

### ISSUE THREAD

**Issue by rgalanakis** [HoneyryderChuck/httpx#66]
If a server returns a `Content-Type: text/html;charset=utf8`, HTTPX will error when calling `force_encoding('utf8')` because it's an invalid encoding. It should be `utf-8`.

This is surprisingly common, despite it being an invalid encoding name. Other libraries like Net::Http handle it, but I'm not sure how. Maybe we need a way to hook into `HTTPX::Response::Body`- I know you can muck around with things to provide custom classes, but an HTTP library is often used several layers deep in other libraries, which prohibits that sort of deep customization.

In the meantime, I'm doing something like this:

```ruby
class HTTPX::Response::Body
  alias _original_initialize initialize
  def initialize(*)
    _original_initialize(*)
    # If the encoding is an invalid one like 'utf8' vs 'utf-8', modify what's was in the charset.
    # See https://github.com/HoneyryderChuck/httpx/issues/66
    return unless @encoding.is_a?(String) && (md = @encoding.match(/^(utf)(\d+)$/))
    @encoding = "#{md[1]}-#{md[2]}"
  end
end
```

**Comment by rgalanakis** [comment]
I guess there is some callbacks system, but I can't find documentation on it. Would that be the place to do something like this, modifying the `response.content_type.charset` (or even before that is set`?

**Comment by HoneyryderChuck** [comment]
Hi @rgalanakis , thx for the report. Can you provide a repro?

**Comment by rgalanakis** [comment]
Run a webserver with the wrong content-type:

```rb
require 'socket'
server  = TCPServer.new('localhost', 18018)
loop {
  client  = server.accept
  client.readpartial(2048)
  client.write("HTTP/1.1 200\r\n" +
    "Content-Length: 2\r\n" +
    "Content-Type: text/plain;charset=utf8\r\n" +
    "\r\n" +
    "hi\r\n")
}
```

Make a request, and stream the response:

```rb
resp = HTTPX.plugin(:stream).request('GET', URI('http://localhost:18018'), stream: true)
resp.headers
# => {"content-length"=>"2", "content-type"=>"text/plain;charset=utf8"}
resp.each { |line| puts line }
# ArgumentError: unknown encoding name - utf8
# from /Users/rob/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/httpx-1.3.3/lib/httpx/response/body.rb:83:in `force_encoding'
```

Note that if you get rid of the `resp.headers` line, the bug doesn't happen. It seems like the encoding isn't read at all, so it defaults to binary encoding (actually I think this is how the other libraries handle an unknown encoding).

This is using a `charset=utf-16`:

```
[68] pry(main)> resp = HTTPX.plugin(:stream).request('GET', URI('http://localhost:18018'), stream: true); resp.each.to_a.first.encoding
=> #<Encoding:ASCII-8BIT>
[69] pry(main)> resp = HTTPX.plugin(:stream).request('GET', URI('http://localhost:18018'), stream: true); resp.headers; resp.each.to_a.first.encoding
=> #<Encoding:UTF-16 (dummy)>
```

**Comment by HoneyryderChuck** [comment]
feel free to try the master branch and see if it fixed your issue.
