### ISSUE TITLE
Do http proxying options need to be set up manually? Is no_proxy ENV variable handled by default?

### ISSUE THREAD

**Issue by paneq** [HoneyryderChuck/httpx#9]
Hey 👋🏻 

Does httpx handle ENV variables responsible for proxying automatically or does it need to be done manually?

* [0.12 release notes](https://github.com/HoneyryderChuck/httpx/blob/31013ba0dd119be131dfea2aeda40887d3633b2b/doc/release_notes/0_12_0.md) mention "Fixed auto-load of :proxy plugin when HTTPS_PROXY or HTTP_PROXY is set".
  * I guess this code now lives [here](https://github.com/HoneyryderChuck/httpx/blob/c1402f7995ac97cc4252c3b5feadbe8bb4c0beb9/lib/httpx/session_extensions.rb#L3-L17)
  * This code seems to set the proxy plugin, but it does not seem to use the ENV variables such as `https_proxy`, `http_proxy`, and `no_proxy` in any way.
  * It seems that it's the [find_proxy](https://apidock.com/ruby/URI/Generic/find_proxy) method responsibility to handle it [implicitly](https://github.com/HoneyryderChuck/httpx/blob/31013ba0dd119be131dfea2aeda40887d3633b2b/lib/httpx/plugins/proxy.rb#L101).

Our tests showcased unexpected behavior where proxying is working but not fully in relation to supporting no_proxy variable:

```bash
# step 1: spin up hoverfly
docker run --rm --name hoverfly -p 8500:8500 -p 8888:8888 spectolabs/hoverfly
```

```ruby
# now enter irb and prepare the environment
require 'httpx'
require 'syrphid'

client = Syrphid::Client.new('http://localhost:8888')
ENV['http_proxy'] = 'http://localhost:8500'               # Set http_proxy environment variable after loading the gem
                                                          # so that the proxy plugin is not used automatically

# craft a simulation (aka stubbed response)
request = ::Syrphid::Simulation::Request.new
request.path = [::Syrphid::Simulation::Request::Matcher.new('exact', '/status/418')]

response = ::Syrphid::Simulation::Response.new
response.body = "I'm two teapots!"                        # different response from proxy

sim = ::Syrphid::Simulation.new
sim << ::Syrphid::Simulation::Pair.new(request, response)

client.add_simulation(sim)

# NOW FOR THE ACTUAL EXPERIMENT

# ok, proxied
HTTPX.plugin(:proxy).get('http://httpbingo.org/status/418').to_s
=> "I'm two teapots!"

# ok, not proxied. :proxy plugin was not loaded automatically because ENV headers were set after the library was loaded
HTTPX.get('http://httpbingo.org/status/418').to_s
=> "I'm a teapot!"


# Disable proxying for the domain that we are using.
ENV['no_proxy'] = 'httpbingo.org'

# Fails
HTTPX.plugin(:proxy).get('http://httpbingo.org/status/418').to_s
Traceback (most recent call last):
...
HTTPX::HTTPProxyError (Failed to connect to proxy)

# works ok with explicitly passing the ENV values to the library. It properly returns the unproxied response.
HTTPX.plugin(:proxy).with_proxy(uri: ENV['http_proxy'], no_proxy: ENV['no_proxy']).get('http://httpbingo.org/status/418').to_s
=> "I'm a teapot!"
```

So the question is what's the expected behavior in regards to handling `no_proxy` automatically? Is it supported or not?

**Comment by HoneyryderChuck** [comment]
Hi @paneq ,

Trying to wrap my head around it, loading `http_proxy` envvar after requiring `httpx` is definitely unusual behaviour, and I'd expect in such a case that you'd do it manually instead of relying on the env var handling instead.

> # Fails
> HTTPX.plugin(:proxy).get('http://httpbingo.org/status/418').to_s
> Traceback (most recent call last):
> ...
> HTTPX::HTTPProxyError (Failed to connect to proxy)

This seems like a bug. What seems to be happening is that:

* http proxy is set, so the loop for "best available proxy" starts;
* the proxy setting gets ignored for `httpbingo.org`;
* the error is raised [here](https://github.com/HoneyryderChuck/httpx/blob/31013ba0dd119be131dfea2aeda40887d3633b2b/lib/httpx/plugins/proxy.rb#L122)
* there's also [this code](https://github.com/HoneyryderChuck/httpx/blob/31013ba0dd119be131dfea2aeda40887d3633b2b/lib/httpx/plugins/proxy.rb#L110), which would treat the current hostname as a proxy(?). Doesn't seem right;

I'll have a look.

**Comment by paneq** [comment]
Thank you!

> http_proxy envvar after requiring httpx is definitely unusual behaviou

This was only done for demonstration purposes so that we could see with and without proxy plugin and with explicit options as well for comparison. In production we set those environment variables outside of the program.

**Comment by HoneyryderChuck** [comment]
@paneq can you try [this branch](https://gitlab.com/os85/httpx/-/tree/fix-no-proxy) and see if it fixes the issue?

**Comment by paneq** [comment]
@HoneyryderChuck I am going for a few weeks of vacations, but I passed this info to another engineer.

**Comment by HoneyryderChuck** [comment]
@paneq any updates?

**Comment by paneq** [comment]
@HoneyryderChuck we should check within 2 weeks.

**Comment by HoneyryderChuck** [comment]
@CrazyPit thx for the heads-up. Will merge and include it in the upcoming release 👍 feel free to use the master branch til then.

**Comment by CrazyPit** [comment]
Thank you!
